GET http://localhost:8080/api/cart
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJuYWl0aWtwYXRlbEBnbWFpbC5jb20iLCJyb2xlIjoidXNlciIsImlhdCI6MTczNTYxOTQ0NCwiZXhwIjoxNzM1NjIzMDQ0fQ.2xv-jfRXB4U66WWwf5_PfI3mLaxb8kaHNzLVNEwgPqE

###
PUT http://localhost:8080/api/cart
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJuYWl0aWtwYXRlbEBnbWFpbC5jb20iLCJyb2xlIjoidXNlciIsImlhdCI6MTczNTYxOTQ0NCwiZXhwIjoxNzM1NjIzMDQ0fQ.2xv-jfRXB4U66WWwf5_PfI3mLaxb8kaHNzLVNEwgPqE

{
  "productId": 2,
  "quantity": 1
}