POST http://localhost:8080/api/products/add
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJhZG1pbkBnbWFpbC5jb20iLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3MzQ0OTU0MTcsImV4cCI6MTczNDQ5OTAxN30.pcD91ajmIOKXCO_m4G-pV8EizuBCW9iwT3oweNqJE08

{
  "name": "Mens Tshirt",
  "description": "Sports Tshirt for mens",
  "price": 100,
  "rating": 4.5,
  "stock": 100,
  "image": "https://via.placeholder.com/150",
  "category_id": 2,
  "brand_id": 3
}

###

GET http://localhost:8080/api/products/all
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJhZG1pbkBnbWFpbC5jb20iLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3MzQ0OTU0MTcsImV4cCI6MTczNDQ5OTAxN30.pcD91ajmIOKXCO_m4G-pV8EizuBCW9iwT3oweNqJE08
###

GET http://localhost:8080/api/brands/all
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJhZG1pbkBnbWFpbC5jb20iLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3MzQ0OTE2NzUsImV4cCI6MTczNDQ5NTI3NX0.TkW5yhMUEhEva1N8JN2sNgoCEaSBgxfmDk5xkCcQKCk

###

POST http://localhost:8080/api/categories/add
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJhZG1pbkBnbWFpbC5jb20iLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3MzQ0OTE2NzUsImV4cCI6MTczNDQ5NTI3NX0.TkW5yhMUEhEva1N8JN2sNgoCEaSBgxfmDk5xkCcQKCk

{
  "name": "Clothes"
}

###

POST http://localhost:8080/api/brands/add
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJhZG1pbkBnbWFpbC5jb20iLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3MzQ0OTE2NzUsImV4cCI6MTczNDQ5NTI3NX0.TkW5yhMUEhEva1N8JN2sNgoCEaSBgxfmDk5xkCcQKCk

{
  "name": "Flying machine"
}